# ansible-playbook -u pi -k -i 'TARGET-DHCP-IP,' lockdown.yml

- name: Application server specific playbook
  hosts: all
  become: yes
  roles:
     - update
     - delete-pi-user
     - set-hostname
     - disable-wireless
     - create-user
     - disable-passwords
     - static-ip
     - expand-filesystem
     - configure-bash

  vars:
    - inventory_hostname: "net0001"
    - username: "richardslater"
    - comment: "Richard Slater (richard@slaterfamily.name)"
    - public_key: "/mnt/c/Users/Richard Slater/.ssh/richard@richard-slater.co.uk-2018.ed25519.pub"
    - interface: "eth0"
    - ipaddress: "10.229.1.5"
    - routers: "10.229.0.1"
    - dns_servers: "1.1.1.1 1.0.0.1"

  vars_prompt:
    - name: "password"
      prompt: "Password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
