# ansible-playbook -i hosts network.yml
---

- name: Raspberry Pi based Pi-Hole
  hosts: net0001
  become: yes
  roles:
     - update
     - delete-pi-user
     - set-hostname
     - disable-wireless
     - create-user
     - disable-passwords
     - static-ip
     - expand-filesystem
     - configure-bash
     - admin-tools
     - install-ntp
     - docker
     - cloudflared
     - pihole

  vars:
    - inventory_hostname: "net0001"
    - username: "richardslater"
    - comment: "Richard Slater (richard@slaterfamily.name)"
    - public_key: "/mnt/c/Users/Richard Slater/.ssh/richard@richard-slater.co.uk-2018.ed25519.pub"
    - interface: "eth0"
    - ipaddress: "10.229.1.5"
    - cidr: "16"
    - routers: "10.229.0.1"
    - dns_servers: [
      "1.1.1.1", 
      "1.0.0.1"
    ]
    - toplevel_timeservers: [
        '0.uk.pool.ntp.org',
        '1.uk.pool.ntp.org',
        '2.uk.pool.ntp.org',
        '3.uk.pool.ntp.org',
        '0.europe.pool.ntp.org',
        '1.europe.pool.ntp.org',
        '2.europe.pool.ntp.org',
        '3.europe.pool.ntp.org'
      ]

  vars_files:
    - secrets.yml
