- name: Install admin tools
  package:
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 2
  with_items:
    - python-apt
    - python-pip
    - vim
    - htop
    - nmap
    - atop
