# roles\admin-tools\main.yml
---
- name: Install admin tools
  apt:
    package: [ "python-apt", "python-pip", "vim", "htop", "nmap", "atop", "ufw" ]
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
