---
- name: stop ntp
  service: name=ntp state=stopped
  when: ansible_hostname != timelord

- name: force ntp update
  command: "ntpdate -s {{ hostvars[groups[timelord][0]]['ansible_' ~ ntp_netdevice]['ipv4']['address'] }}"
  when: ansible_hostname != timelord

- name: start ntp
  service: name=ntp state=started
  when: ansible_hostname != timelord

- name: restart ntp
  service: name=ntp state=restarted
  when: ansible_hostname == timelord
