---
- name: stop ntp
  service: name=ntp state=stopped

- name: force ntp update
  command: "ntpdate -s {{ toplevel_timeservers[0] }}"

- name: start ntp
  service: name=ntp state=started

- name: restart ntp
  service: name=ntp state=restarted
